package br.com.fatec.view;

import br.com.fatec.DAO.DrugDAO;
import br.com.fatec.model.Drug;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListOrders extends javax.swing.JFrame {
    Drug drug;
    DrugDAO drugDAO = new DrugDAO();
    int cod;
    DefaultTableModel tabelModel;
    /**
     * Creates new form RegisterDrug
     */
    public ListOrders() throws ParseException {
        initComponents();
        TableFill();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBack1 = new rojeru_san.RSButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ExpíryText = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            ExpíryText = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel4 = new javax.swing.JLabel();
        LabText = new javax.swing.JTextField();
        RGText = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##.###.###-#");
            RGText = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel7 = new javax.swing.JLabel();
        btEdit = new rojeru_san.RSButton();
        btBack = new rojeru_san.RSButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDrug = new javax.swing.JTable();
        btDelete = new rojeru_san.RSButton();
        jLabel9 = new javax.swing.JLabel();
        PriceText = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter price= new javax.swing.text.MaskFormatter("###.##");
            PriceText = new javax.swing.JFormattedTextField(price);
        }
        catch (Exception e){
        }
        TypeText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescText = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        PrescCombo = new javax.swing.JComboBox<>();
        GenericCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btBack2 = new rojeru_san.RSButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        btBack1.setBackground(new java.awt.Color(1, 198, 83));
        btBack1.setText("Voltar");
        btBack1.setColorHover(new java.awt.Color(0, 102, 51));
        btBack1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Medicamento");
        setMinimumSize(new java.awt.Dimension(890, 730));
        setResizable(false);
        setSize(getMinimumSize());
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nome Comercial");

        NameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameText.setBorder(null);
        NameText.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Tipo");

        ExpíryText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExpíryText.setBorder(null);
        ExpíryText.setEnabled(false);
        ExpíryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpíryTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Laboratório");

        LabText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabText.setBorder(null);
        LabText.setEnabled(false);

        RGText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RGText.setBorder(null);
        RGText.setEnabled(false);
        RGText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Preço");

        btEdit.setBackground(new java.awt.Color(255, 51, 51));
        btEdit.setText("Editar");
        btEdit.setColorHover(new java.awt.Color(153, 0, 0));
        btEdit.setEnabled(false);
        btEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btBack.setBackground(new java.awt.Color(255, 51, 51));
        btBack.setText("Voltar");
        btBack.setColorHover(new java.awt.Color(153, 0, 0));
        btBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Gerenciamento de Medicamento");

        tbDrug.setBackground(new java.awt.Color(204, 204, 204));
        tbDrug.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbDrug.setToolTipText("");
        tbDrug.setGridColor(new java.awt.Color(255, 255, 255));
        tbDrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDrugMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDrug);

        btDelete.setBackground(new java.awt.Color(255, 51, 51));
        btDelete.setText("Excluir");
        btDelete.setColorHover(new java.awt.Color(153, 0, 0));
        btDelete.setEnabled(false);
        btDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Validade");

        PriceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PriceText.setBorder(null);
        PriceText.setEnabled(false);
        PriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTextActionPerformed(evt);
            }
        });

        TypeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TypeText.setBorder(null);
        TypeText.setEnabled(false);
        TypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTextActionPerformed(evt);
            }
        });

        DescText.setColumns(20);
        DescText.setRows(5);
        DescText.setEnabled(false);
        jScrollPane2.setViewportView(DescText);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Descrição");

        PrescCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        PrescCombo.setEnabled(false);

        GenericCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        GenericCombo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("É genérico");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Exige Prescrição");

        btBack2.setBackground(new java.awt.Color(255, 51, 51));
        btBack2.setText("Voltar");
        btBack2.setColorHover(new java.awt.Color(153, 0, 0));
        btBack2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jScrollPane2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(GenericCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(PrescCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LabText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(91, 91, 91))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ExpíryText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(389, 389, 389)
                                .addComponent(RGText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(472, 472, 472)))
                                .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RGText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ExpíryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(PriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenericCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrescCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(112, 0, 770, 710);

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setForeground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 110, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        new DrugOptions().setVisible(true);
        dispose();  
    }//GEN-LAST:event_btBackActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        drug = new Drug();
        drug.setComname(NameText.getText());
        drug.setTypedrug(TypeText.getText());
        drug.setLab(LabText.getText());
        drug.setUnitprice(Float.parseFloat(PriceText.getText()));
        drug.setDateshelf(ConvertDateToDatabase(ExpíryText.getText()));
        drug.setDescdrug(DescText.getText()); 
        drug.setIsgeneric(GenericCombo.getSelectedIndex());
        drug.setNeedpre(PrescCombo.getSelectedIndex());
        drug.setIdDrug(cod);
        try {
            if(drugDAO.edit(drug)) {
                JOptionPane.showMessageDialog(this,
                        "Cadastro Alterado com Sucesso!",
                        "Mensagem ao Usuário",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this,
                        "Erro ao Alterar",
                        "Mensagem ao Usuário",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                        "Erro SQL " + ex.getMessage(),
                        "Mensagem ao Usuário",
                        JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,
                        "Erro Class " + ex.getMessage(),
                        "Mensagem ao Usuário",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void RGTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RGTextActionPerformed

    private void tbDrugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDrugMouseClicked
        int line = tbDrug.getSelectedRow();
        cod = (Integer)tbDrug.getValueAt(line, 0);
        try {
            Drug d = new Drug();
            d.setIdDrug(cod);
            d = drugDAO.search(d);
            
            String zeros = "00000";
            String numero = zeros + Float.toString(d.getUnitprice()).replace(".", "");
            String test =  numero.substring(numero.length() - 5);
            StringBuilder stringBuilder = new StringBuilder(test);
            stringBuilder.insert(test.length(), '0');
            if(d != null) {
                //jogar dados para a tela
                NameText.setText(d.getComname());
                LabText.setText(d.getLab());
                DescText.setText(d.getDescdrug());
                PriceText.setText(test);
                TypeText.setText(d.getTypedrug());
                ExpíryText.setText(ConvertDateToString(d.getDateshelf()));
                GenericCombo.setSelectedIndex(d.getIsgeneric());
                PrescCombo.setSelectedIndex(d.getNeedpre());
                Enable();
            }
            else {
                JOptionPane.showMessageDialog(this, 
                        "Medicamento não Encontrado",
                        "Mensagem ao Usuário",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ListOrders.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListOrders.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tbDrugMouseClicked

    private void ExpíryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpíryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpíryTextActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int resp;
        resp = JOptionPane.showConfirmDialog(this,"Deseja realmente excluir?", "Mensagem ao Usuário", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(resp == JOptionPane.YES_OPTION){
            drug = new Drug();
            drug.setIdDrug(cod);
            try {
                if(drugDAO.delete(drug)) {
                    JOptionPane.showMessageDialog(this, "Cliente excluido com sucesso", "Mensagem ao Usuário", JOptionPane.INFORMATION_MESSAGE);
                    Clear();
                    TableFill();
                    Disable();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Erro ao Excluir","Mensagem ao Usuário", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro SQL " + ex.getMessage(), "Mensagem ao Usuário", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Erro Class " + ex.getMessage(), "Mensagem ao Usuário", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void PriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTextActionPerformed

    private void TypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeTextActionPerformed

    private void btBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack1ActionPerformed
    }//GEN-LAST:event_btBack1ActionPerformed

    private void btBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack2ActionPerformed
        new DrugOptions().setVisible(true);
        dispose();
    }//GEN-LAST:event_btBack2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListOrders().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(ListOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescText;
    private javax.swing.JTextField ExpíryText;
    private javax.swing.JComboBox<String> GenericCombo;
    private javax.swing.JTextField LabText;
    private javax.swing.JTextField NameText;
    private javax.swing.JComboBox<String> PrescCombo;
    private javax.swing.JTextField PriceText;
    private javax.swing.JTextField RGText;
    private javax.swing.JTextField TypeText;
    private rojeru_san.RSButton btBack;
    private rojeru_san.RSButton btBack1;
    private rojeru_san.RSButton btBack2;
    private rojeru_san.RSButton btDelete;
    private rojeru_san.RSButton btEdit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDrug;
    // End of variables declaration//GEN-END:variables
    private void Clear() {
        DescText.setText("");
        NameText.setText("");
        LabText.setText("");
        ExpíryText.setText("");
        PriceText.setText("");  
        TypeText.setText("");
    }    
    private void Enable() {
        NameText.setEnabled(true);
        LabText.setEnabled(true);
        ExpíryText.setEnabled(true);
        PriceText.setEnabled(true);
        TypeText.setEnabled(true);
        DescText.setEnabled(true);
        PrescCombo.setEnabled(true);
        GenericCombo.setEnabled(true);
        btDelete.setEnabled(true);
        btEdit.setEnabled(true);
    }
    private void Disable() {
        NameText.setEnabled(false);
        LabText.setEnabled(false);
        ExpíryText.setEnabled(false);
        PriceText.setEnabled(false);
        TypeText.setEnabled(false);
        DescText.setEnabled(false);
        PrescCombo.setEnabled(false);
        GenericCombo.setEnabled(false);
        btDelete.setEnabled(false);
        btEdit.setEnabled(false);
    }
    
    public String ConvertDateToDatabase(String date) {
        java.util.Date formatDate;
        String databaseDate = "";
        try {
            formatDate = new SimpleDateFormat("dd/MM/yyyy").parse(date);
            databaseDate = new SimpleDateFormat("yyyy-MM-dd").format(formatDate);
        } catch (ParseException ex) {
            Logger.getLogger(ListOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
        return databaseDate;
    }
    public String ConvertDateToString(String date) {
        java.util.Date formatDate;
        String databaseDate = "";
        try {
            formatDate = new SimpleDateFormat("yyyy-MM-dd").parse(date);
            databaseDate = new SimpleDateFormat("ddMMyyyy").format(formatDate);
        } catch (ParseException ex) {
            Logger.getLogger(ListOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
        return databaseDate;
    }
    private void TableFill() {
        try {
            List<Drug> data = drugDAO.list("");

            Vector<String> header = new Vector<>(3);
            header.add("Código");
            header.add("Nome Comercial");
            header.add("Tipo");
            
            Vector lines = new Vector();
            Vector record = new Vector();
            
            for(Drug c : data) {
                record = new Vector(3);
                record.add(c.getIdDrug());
                record.add(c.getComname());
                record.add(c.getTypedrug());
                lines.add(record);                
            }
            
            //coloca os vetores no modelo da tabela
            tabelModel = new DefaultTableModel(lines, header);
            
            //jogar o modelo dentro do jtable
            tbDrug.setModel(tabelModel);
            
            //ajustar tamanhos das colunas
            tbDrug.getColumnModel().getColumn(0)
                    .setPreferredWidth(70);
            tbDrug.getColumnModel().getColumn(1)
                    .setPreferredWidth(350);
            tbDrug.getColumnModel().getColumn(2)
                    .setPreferredWidth(100);
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(ListOrders.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(ListOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}